from django.urls import path, include
from rest_framework import routers
from .views import ConversationViewSet, MessageViewSet

# ✅ Create a DRF DefaultRouter instance
router = routers.DefaultRouter()
router.register(r'conversations', ConversationViewSet, basename='conversation')
router.register(r'messages', MessageViewSet, basename='message')

urlpatterns = [
    # ✅ Include all routes generated by DefaultRouter
    path('', include(router.urls)),
]


from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from chats.views import ConversationViewSet, MessageViewSet  # Adjust app name if different

# Create a DRF router and register your viewsets
router = DefaultRouter()
router.register(r'conversations', ConversationViewSet, basename='conversation')
router.register(r'messages', MessageViewSet, basename='message')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),  # All API endpoints will start with /api/
]
